apiVersion: v1
kind: BuildConfig
metadata:
  name: springboot-pipepline
  labels:
    name: springboot-pipepline
  annotations:
    pipeline.alpha.openshift.io/uses: '[{"name": "springboot", "namespace": "", "kind": "DeploymentConfig"}]'
spec:
  triggers:
    - 
      type: GitHub
      github:
        secret: 81dedc21cc8f7b72
    - 
      type: Generic
      generic:
        secret: 81dedc21cc8f7b72  
  runPolicy: Serial
  source:
    type: None  
  strategy:
    type: JenkinsPipeline
    jenkinsPipelineStrategy:
      jenkinsfile: |-
        node {
          stage('build'){
            openshiftBuild(buildConfig: 'springboot', showBuildLogs: 'true')
          }
          stage('deploy'){
            openshiftDeploy(deploymentConfig: 'springboot')
            openshiftScale(deploymentConfig: 'springboot', replicaCount: '3')
          }
        }
  output:
  resources:
  postCommit:
  
